export { default as person1 } from './testimonial-1.png'
export { default as person2 } from './testimonial-2.png'
export { default as person3 } from './testimonial-3.png'
export { default as person4 } from './testimonial-4.png'
export { default as person5 } from './testimonial-5.png'
