export { default as Woman1 } from './woman-applying-face-cream-1.png'
export { default as Woman2 } from './woman-applying-face-cream-2.png'
export { default as Woman3 } from './woman-applying-face-cream-3.png'
export { default as Woman4 } from './woman-applying-face-cream-4.png'
export { default as Woman5 } from './woman-applying-face-cream-5.png'
